# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import Activity
    from ._models_py3 import AnimationCard
    from ._models_py3 import Attachment
    from ._models_py3 import AttachmentData
    from ._models_py3 import AttachmentInfo
    from ._models_py3 import AttachmentView
    from ._models_py3 import AudioCard
    from ._models_py3 import BasicCard
    from ._models_py3 import CardAction
    from ._models_py3 import CardImage
    from ._models_py3 import ChannelAccount
    from ._models_py3 import ConversationAccount
    from ._models_py3 import ConversationMembers
    from ._models_py3 import ConversationParameters
    from ._models_py3 import ConversationReference
    from ._models_py3 import ConversationResourceResponse
    from ._models_py3 import ConversationsResult
    from ._models_py3 import Entity
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse, ErrorResponseException
    from ._models_py3 import Fact
    from ._models_py3 import GeoCoordinates
    from ._models_py3 import HeroCard
    from ._models_py3 import InnerHttpError
    from ._models_py3 import MediaCard
    from ._models_py3 import MediaEventValue
    from ._models_py3 import MediaUrl
    from ._models_py3 import Mention
    from ._models_py3 import MessageReaction
    from ._models_py3 import OAuthCard
    from ._models_py3 import PagedMembersResult
    from ._models_py3 import Place
    from ._models_py3 import ReceiptCard
    from ._models_py3 import ReceiptItem
    from ._models_py3 import ResourceResponse
    from ._models_py3 import SemanticAction
    from ._models_py3 import SigninCard
    from ._models_py3 import SuggestedActions
    from ._models_py3 import TextHighlight
    from ._models_py3 import Thing
    from ._models_py3 import ThumbnailCard
    from ._models_py3 import ThumbnailUrl
    from ._models_py3 import TokenRequest
    from ._models_py3 import TokenResponse
    from ._models_py3 import Transcript
    from ._models_py3 import VideoCard
except (SyntaxError, ImportError):
    from ._models import Activity
    from ._models import AnimationCard
    from ._models import Attachment
    from ._models import AttachmentData
    from ._models import AttachmentInfo
    from ._models import AttachmentView
    from ._models import AudioCard
    from ._models import BasicCard
    from ._models import CardAction
    from ._models import CardImage
    from ._models import ChannelAccount
    from ._models import ConversationAccount
    from ._models import ConversationMembers
    from ._models import ConversationParameters
    from ._models import ConversationReference
    from ._models import ConversationResourceResponse
    from ._models import ConversationsResult
    from ._models import Entity
    from ._models import Error
    from ._models import ErrorResponse, ErrorResponseException
    from ._models import Fact
    from ._models import GeoCoordinates
    from ._models import HeroCard
    from ._models import InnerHttpError
    from ._models import MediaCard
    from ._models import MediaEventValue
    from ._models import MediaUrl
    from ._models import Mention
    from ._models import MessageReaction
    from ._models import OAuthCard
    from ._models import PagedMembersResult
    from ._models import Place
    from ._models import ReceiptCard
    from ._models import ReceiptItem
    from ._models import ResourceResponse
    from ._models import SemanticAction
    from ._models import SigninCard
    from ._models import SuggestedActions
    from ._models import TextHighlight
    from ._models import Thing
    from ._models import ThumbnailCard
    from ._models import ThumbnailUrl
    from ._models import TokenRequest
    from ._models import TokenResponse
    from ._models import Transcript
    from ._models import VideoCard
from ._connector_client_enums import (
    ActionTypes,
    ActivityImportance,
    ActivityTypes,
    AttachmentLayoutTypes,
    ContactRelationUpdateActionTypes,
    DeliveryModes,
    EndOfConversationCodes,
    InputHints,
    InstallationUpdateActionTypes,
    MessageReactionTypes,
    RoleTypes,
    TextFormatTypes,
)

__all__ = [
    "Activity",
    "AnimationCard",
    "Attachment",
    "AttachmentData",
    "AttachmentInfo",
    "AttachmentView",
    "AudioCard",
    "BasicCard",
    "CardAction",
    "CardImage",
    "ChannelAccount",
    "ConversationAccount",
    "ConversationMembers",
    "ConversationParameters",
    "ConversationReference",
    "ConversationResourceResponse",
    "ConversationsResult",
    "Entity",
    "Error",
    "ErrorResponse",
    "ErrorResponseException",
    "Fact",
    "GeoCoordinates",
    "HeroCard",
    "InnerHttpError",
    "MediaCard",
    "MediaEventValue",
    "MediaUrl",
    "Mention",
    "MessageReaction",
    "OAuthCard",
    "PagedMembersResult",
    "Place",
    "ReceiptCard",
    "ReceiptItem",
    "ResourceResponse",
    "SemanticAction",
    "SigninCard",
    "SuggestedActions",
    "TextHighlight",
    "Thing",
    "ThumbnailCard",
    "ThumbnailUrl",
    "TokenRequest",
    "TokenResponse",
    "Transcript",
    "VideoCard",
    "RoleTypes",
    "ActivityTypes",
    "TextFormatTypes",
    "AttachmentLayoutTypes",
    "MessageReactionTypes",
    "InputHints",
    "ActionTypes",
    "EndOfConversationCodes",
    "ActivityImportance",
    "DeliveryModes",
    "ContactRelationUpdateActionTypes",
    "InstallationUpdateActionTypes",
]
