# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AttachmentData(Model):
    """Attachment data.

    :param type: Content-Type of the attachment
    :type type: str
    :param name: Name of the attachment
    :type name: str
    :param original_base64: Attachment content
    :type original_base64: bytearray
    :param thumbnail_base64: Attachment thumbnail
    :type thumbnail_base64: bytearray
    """

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'original_base64': {'key': 'originalBase64', 'type': 'bytearray'},
        'thumbnail_base64': {'key': 'thumbnailBase64', 'type': 'bytearray'},
    }

    def __init__(self, *, type: str=None, name: str=None, original_base64: bytearray=None, thumbnail_base64: bytearray=None, **kwargs) -> None:
        super(AttachmentData, self).__init__(**kwargs)
        self.type = type
        self.name = name
        self.original_base64 = original_base64
        self.thumbnail_base64 = thumbnail_base64
