# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ConversationMembers(Model):
    """Conversation and its members.

    :param id: Conversation ID
    :type id: str
    :param members: List of members in this conversation
    :type members: list[~botframework.connector.models.ChannelAccount]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'members': {'key': 'members', 'type': '[ChannelAccount]'},
    }

    def __init__(self, **kwargs):
        super(ConversationMembers, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.members = kwargs.get('members', None)
