# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class PaymentRequestComplete(Model):
    """Payload delivered when completing a payment request.

    :param id: Payment request ID
    :type id: str
    :param payment_request: Initial payment request
    :type payment_request: ~botframework.connector.models.PaymentRequest
    :param payment_response: Corresponding payment response
    :type payment_response: ~botframework.connector.models.PaymentResponse
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'payment_request': {'key': 'paymentRequest', 'type': 'PaymentRequest'},
        'payment_response': {'key': 'paymentResponse', 'type': 'PaymentResponse'},
    }

    def __init__(self, *, id: str=None, payment_request=None, payment_response=None, **kwargs) -> None:
        super(PaymentRequestComplete, self).__init__(**kwargs)
        self.id = id
        self.payment_request = payment_request
        self.payment_response = payment_response
