# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TextHighlight(Model):
    """TextHighlight.

    :param text: plain text fragment to highlight
    :type text: str
    :param occurence: index of occurence of the Text (Starting at 1)
    :type occurence: int
    """

    _attribute_map = {
        'text': {'key': 'text', 'type': 'str'},
        'occurence': {'key': 'occurence', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(TextHighlight, self).__init__(**kwargs)
        self.text = kwargs.get('text', None)
        self.occurence = kwargs.get('occurence', None)
