# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class TokenRequest(Model):
    """A request to receive a user token.

    :param provider: The provider to request a user token from
    :type provider: str
    :param settings: A collection of settings for the specific provider for
     this request
    :type settings: dict[str, object]
    """

    _attribute_map = {
        'provider': {'key': 'provider', 'type': 'str'},
        'settings': {'key': 'settings', 'type': '{object}'},
    }

    def __init__(self, *, provider: str=None, settings=None, **kwargs) -> None:
        super(TokenRequest, self).__init__(**kwargs)
        self.provider = provider
        self.settings = settings
