RUN apt-get update -y && \
    apt-get install -y software-properties-common
RUN apt-add-repository ppa:deadsnakes/ppa -y
RUN apt-get update
RUN apt-get install -y python3.6-dev
RUN apt-get install -y curl
RUN apt-get install -y gcc
RUN apt-get install -y locales-all
