default_stages: [push]
repos:
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    -   id: pylint
        files: libraries
        args:
        -   --rcfile=.pylintrc
        always_run: true
        verbose: true