# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

class ChannelInfo:
    def __init__(self, id = "", name = ""):
        self._id = id
        self._name = name
    
    @property
    def id(self):
        return self._id
    
    @id.setter
    def id(self, id):
        self._id = id
    
    @property 
    def name(self):
        return self._name

    @name.setter
    def name(self, name):
        self._name = name