# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class FileConsentCard(Model):
    """File consent card attachment.

    :param description: File description.
    :type description: str
    :param size_in_bytes: Size of the file to be uploaded in Bytes.
    :type size_in_bytes: long
    :param accept_context: Context sent back to the Bot if user consented to
     upload. This is free flow schema and is sent back in Value field of
     Activity.
    :type accept_context: object
    :param decline_context: Context sent back to the Bot if user declined.
     This is free flow schema and is sent back in Value field of Activity.
    :type decline_context: object
    """

    _attribute_map = {
        "description": {"key": "description", "type": "str"},
        "size_in_bytes": {"key": "sizeInBytes", "type": "long"},
        "accept_context": {"key": "acceptContext", "type": "object"},
        "decline_context": {"key": "declineContext", "type": "object"},
    }

    def __init__(self, **kwargs):
        super(FileConsentCard, self).__init__(**kwargs)
        self.description = kwargs.get("description", None)
        self.size_in_bytes = kwargs.get("size_in_bytes", None)
        self.accept_context = kwargs.get("accept_context", None)
        self.decline_context = kwargs.get("decline_context", None)
