# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MessageActionsPayloadUser(Model):
    """Represents a user entity.

    :param user_identity_type: The identity type of the user. Possible values
     include: 'aadUser', 'onPremiseAadUser', 'anonymousGuest', 'federatedUser'
    :type user_identity_type: str or ~botframework.connector.teams.models.enum
    :param id: The id of the user.
    :type id: str
    :param display_name: The plaintext display name of the user.
    :type display_name: str
    """

    _attribute_map = {
        "user_identity_type": {"key": "userIdentityType", "type": "str"},
        "id": {"key": "id", "type": "str"},
        "display_name": {"key": "displayName", "type": "str"},
    }

    def __init__(self, **kwargs):
        super(MessageActionsPayloadUser, self).__init__(**kwargs)
        self.user_identity_type = kwargs.get("user_identity_type", None)
        self.id = kwargs.get("id", None)
        self.display_name = kwargs.get("display_name", None)
