# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

from botbuilder.schema import ChannelAccount


class TeamsChannelAccount(ChannelAccount):
    def __init__(
        self,
        id="",
        name="",
        aad_object_id="",
        role="",
        given_name="",
        surname="",
        email="",
        userPrincipalName="",
    ):
        super().__init__(
            **{"id": id, "name": name, "aad_object_id": aad_object_id, "role": role}
        )
        self.given_name = given_name
        self.surname = surname
        self.email = email
        self.user_principal_name = userPrincipalName
