# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

from botbuilder.schema.teams import ChannelInfo, TeamInfo, NotificationInfo, TenantInfo


class TeamsChannelData:
    def __init__(
        self,
        channel: ChannelInfo = None,
        eventType="",
        team: TeamInfo = None,
        notification: NotificationInfo = None,
        tenant: TenantInfo = None,
    ):
        self.channel = ChannelInfo(**channel) if channel is not None else ChannelInfo()
        # This is not camel case because the JSON that makes this object isn't
        self.event_type = eventType
        self.team = TeamInfo(**team) if team is not None else TeamInfo()
        self.notification = (
            NotificationInfo(**notification)
            if notification is not None
            else NotificationInfo()
        )
        self.tenant = TenantInfo(**tenant) if tenant is not None else TenantInfo()
