# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.


class TeamInfo:
    def __init__(self, id="", name="", aadGroupId=""):
        self._id = id
        self._name = name
        self._aad_group_id = aadGroupId

    def get_id(self):
        return self._id

    def set_id(self, id):
        self._id = id

    def get_name(self):
        return self._name

    def set_name(self, name):
        self._name = name

    def get_aad_group_id(self):
        return self._aad_group_id

    def set_aad_group_id(self, aad_group_id):
        self._aad_group_id = aad_group_id

    id = property(get_id, set_id)
    name = property(get_name, set_name)
    aad_group_id = property(get_aad_group_id, set_aad_group_id)
