# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MessageActionsPayloadReaction(Model):
    """Represents the reaction of a user to a message.

    :param reaction_type: The type of reaction given to the message. Possible
     values include: 'like', 'heart', 'laugh', 'surprised', 'sad', 'angry'
    :type reaction_type: str or ~botframework.connector.teams.models.enum
    :param created_date_time: Timestamp of when the user reacted to the
     message.
    :type created_date_time: str
    :param user: The user with which the reaction is associated.
    :type user: ~botframework.connector.teams.models.MessageActionsPayloadFrom
    """

    _attribute_map = {
        'reaction_type': {'key': 'reactionType', 'type': 'str'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'str'},
        'user': {'key': 'user', 'type': 'MessageActionsPayloadFrom'},
    }

    def __init__(self, **kwargs):
        super(MessageActionsPayloadReaction, self).__init__(**kwargs)
        self.reaction_type = kwargs.get('reaction_type', None)
        self.created_date_time = kwargs.get('created_date_time', None)
        self.user = kwargs.get('user', None)
