"Math"
ADD = "+"
SUBTRACT = "-"
MULTIPLY = "*"
DIVIDE = "/"
MIN = "min"
MAX = "max"
POWER = "^"
MOD = "%"
AVERAGE = "average"
SUM = "sum"
RANGE = "range"
FLOOR = "floor"
CEILING = "ceiling"
ROUND = "round"

"Comparisons"
NOTEQUAL = "!="
EQUAL = "=="
LESSTHAN = "<"
LESSTHANOREQUAL = "<="
GREATERTHAN = ">"
GREATERTHANOREQUAL = ">="
EXIST = "exists"

"Logic"
AND = "&&"
OR = "||"
NOT = "!"

"String"
CONCAT = "concat"
LENGTH = "length"
REPLACE = "replace"
REPLACEIGNORECASE = "replaceIgnoreCase"
SPLIT = "split"
SUBSTRING = "substring"
TOLOWER = "toLower"
TOUPPER = "toUpper"
TRIM = "trim"
ENDSWITH = "endsWith"
STARTSWITH = "startsWith"
COUNTWORD = "countWord"
ADDORDINAL = "addOrdinal"
NEWGUID = "newGuid"
INDEXOF = "indexOf"
LASTINDEXOF = "lastIndexOf"
EOL = "EOL"
SENTENCECASE = "sentenceCase"
TITLECASE = "titleCase"

"Memory"
ACCESSOR = "Accessor"
ELEMENT = "Element"
CREATEARRAY = "createArray"

"Collection"
FOREACH = "foreach"
WHERE = "where"
SELECT = "select"

"DateTime"
ADDDAYS = "addDays"
ADDHOURS = "addHours"
ADDMINUTES = "addMinutes"
ADDSECONDS = "addSeconds"

"Misc"
CONSTANT = "Constant"
LAMBDA = "Lambda"

"Object manipulation and construction functions"
JSON = "json"
SETPROPERTY = "setProperty"
SETPATHTOVALUE = "setPathToValue"
