"Math"
ADD = "+"
SUBTRACT = "-"
MULTIPLY = "*"
DIVIDE = "/"
MIN = "min"
MAX = "max"
POWER = "^"
MOD = "%"
AVERAGE = "average"
SUM = "sum"
RANGE = "range"
FLOOR = "floor"
CEILING = "ceiling"
ROUND = "round"

"Comparisons"
NOTEQUAL = "!="
EQUAL = "=="
LESSTHAN = "<"
LESSTHANOREQUAL = "<="
GREATERTHAN = ">"
GREATERTHANOREQUAL = ">="
EXIST = "exists"


"Logic"
AND = "&&"
OR = "||"
NOT = "!"

"String"
CONCAT = "concat"
LENGTH = "length"
REPLACE = "replace"
REPLACEIGNORECASE = "replaceIgnoreCase"
SPLIT = "split"
SUBSTRING = "substring"

"Memory"
ACCESSOR = "Accessor"
ELEMENT = "Element"
CREATEARRAY = "createArray"

"Collection"
FOREACH = "foreach"
WHERE = "where"
SELECT = "select"

"Misc"
CONSTANT = "Constant"
LAMBDA = "Lambda"

"Object manipulation and construction functions"
JSON = "json"
SETPROPERTY = "setProperty"
SETPATHTOVALUE = "setPathToValue"
