# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CompositeChildModel(Model):
    """Child entity in a LUIS Composite Entity.

    :param type: Type of child entity.
    :type type: str
    :param value: Value extracted by LUIS.
    :type value: str
    """

    _validation = {
        'type': {'required': True},
        'value': {'required': True},
    }

    _attribute_map = {
        'type': {'key': 'type', 'type': 'str'},
        'value': {'key': 'value', 'type': 'str'},
    }

    def __init__(self, type, value):
        super(CompositeChildModel, self).__init__()
        self.type = type
        self.value = value
