__title__ = 'botbuilder-core'
__version__ = '4.0.0.a2'
__uri__ = 'https://www.github.com/Microsoft/botbuilder-python'
__author__ = 'Microsoft'
__description__ = 'Microsoft Bot Framework Bot Builder'
__summary__ = 'Microsoft Bot Framework Bot Builder SDK for Python.'
__license__ = 'MIT'
