# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

try:
    from ._models_py3 import AadResourceUrls
    from ._models_py3 import Error
    from ._models_py3 import ErrorResponse, ErrorResponseException
    from ._models_py3 import InnerHttpError
    from ._models_py3 import TokenResponse
    from ._models_py3 import TokenStatus
except (SyntaxError, ImportError):
    from ._models import AadResourceUrls
    from ._models import Error
    from ._models import ErrorResponse, ErrorResponseException
    from ._models import InnerHttpError
    from ._models import TokenResponse
    from ._models import TokenStatus

__all__ = [
    "AadResourceUrls",
    "Error",
    "ErrorResponse",
    "ErrorResponseException",
    "InnerHttpError",
    "TokenResponse",
    "TokenStatus",
]
