# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from enum import Enum


class ActivityTypes(Enum):

    message = "message"
    contact_relation_update = "contactRelationUpdate"
    conversation_update = "conversationUpdate"
    typing = "typing"
    ping = "ping"
    end_of_conversation = "endOfConversation"
    event = "event"
    invoke = "invoke"
    delete_user_data = "deleteUserData"
    message_update = "messageUpdate"
    message_delete = "messageDelete"
    installation_update = "installationUpdate"
    message_reaction = "messageReaction"
    suggestion = "suggestion"


class TextFormatTypes(Enum):

    markdown = "markdown"
    plain = "plain"
    xml = "xml"


class AttachmentLayoutTypes(Enum):

    list = "list"
    carousel = "carousel"


class MessageReactionTypes(Enum):

    like = "like"
    plus_one = "plusOne"


class InputHints(Enum):

    accepting_input = "acceptingInput"
    ignoring_input = "ignoringInput"
    expecting_input = "expectingInput"


class ActionTypes(Enum):

    open_url = "openUrl"
    im_back = "imBack"
    post_back = "postBack"
    play_audio = "playAudio"
    play_video = "playVideo"
    show_image = "showImage"
    download_file = "downloadFile"
    signin = "signin"
    call = "call"
    payment = "payment"
    message_back = "messageBack"


class EndOfConversationCodes(Enum):

    unknown = "unknown"
    completed_successfully = "completedSuccessfully"
    user_cancelled = "userCancelled"
    bot_timed_out = "botTimedOut"
    bot_issued_invalid_message = "botIssuedInvalidMessage"
    channel_failed = "channelFailed"


class ContactRelationUpdateActionTypes(Enum):

    add = "add"
    remove = "remove"


class InstallationUpdateActionTypes(Enum):

    add = "add"
    remove = "remove"


class ActivityImportance(Enum):

    low = "low"
    normal = "normal"
    high = "high"
