name: pr-style.yml

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  prStyle:
    name: pr-style
    runs-on: ubuntu-latest

    steps:
      - uses: joshgummersall/pr-style@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          require_issue: "true"
          skip_authors: "dependabot"
